[package]
name = "aloroid/gorp-ecr"
description = "gorp implementation for ECR"
license = "MIT"
version = "0.2.0-rc2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
gorp = "aloroid/gorp@0.2.0-rc2"
ecr = "centau/ecr@0.8.0"